const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK';

const REDIRECT_TO_DETAIL = 'REDIRECT_TO_DETAIL';

const SWITCH_CATEGORY = 'SWITCH_CATEGORY';

export { TOGGLE_BOOKMARK, REDIRECT_TO_DETAIL, SWITCH_CATEGORY };
